# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_lik_trans <- function(I_, I1_) {
    .Call(`_eradicate_get_lik_trans`, I_, I1_)
}

nll_multmixOpen <- function(y_, yt_, Xlam_, Xgam_, Xom_, Xp_, Xiota_, beta_, beta_ind_, Xlam_offset_, Xgam_offset_, Xom_offset_, Xp_offset_, Xiota_offset_, ytna_, yna_, lk_, mixture_, first_, last_, first1_, M_, T_, J_, delta_, dynamics_, fix_, go_dims_, immigration_, I_, I1_, Ib_, Ip_, pi_fun_, lfac_k_, kmyt_, lfac_kmyt_, fin_) {
    .Call(`_eradicate_nll_multmixOpen`, y_, yt_, Xlam_, Xgam_, Xom_, Xp_, Xiota_, beta_, beta_ind_, Xlam_offset_, Xgam_offset_, Xom_offset_, Xp_offset_, Xiota_offset_, ytna_, yna_, lk_, mixture_, first_, last_, first1_, M_, T_, J_, delta_, dynamics_, fix_, go_dims_, immigration_, I_, I1_, Ib_, Ip_, pi_fun_, lfac_k_, kmyt_, lfac_kmyt_, fin_)
}

